services:
  mongo_db:
    image: mongo:5.0
    container_name: mongo_db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    image: nodeapp
    container_name: dealers_api
    depends_on:
      - mongo_db
    ports:
      - "3030:3030"

volumes:
  mongo_data: {}
