apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership
  labels:
    run: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        run: dealership
    spec:
      containers:
        - name: dealership
          image: us.icr.io/sn-labs-tonyenra/dealership:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: backend_url
              value: "https://tonyenra-3030.theiadockernext-1-labs-prod-theiak8s-4-tor01.proxy.cognitiveclass.ai"
---
apiVersion: v1
kind: Service
metadata:
  name: dealership
spec:
  selector:
    run: dealership
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
